import "./globals.css";
import { getServerSession } from "next-auth/next";
// import { Inter } from "next/font/google";
import { testAdmin } from "../testAdmin.json";
import { authOptions } from "./api/auth/[...nextauth]/route";
// import Provider from "../components/Provider";
import Navbar from "../components/UI/Navbar";
import Footer from "../components/UI/Footer";
// import About from "./about/page";

// const inter = Inter({ subsets: ["latin"] });
console.log("🚀 ~ file: layout.jsx:5 ~ bbbbbb:", testAdmin);

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  console.log("🚀 ~ file: layout.jsx:19 ~ RootLayout ~ session:", session);
  let role = "";
  if (testAdmin.includes(session?.user?.email)) {
    // return <p>You are an admin, welcome!</p>;
    role = "admin";
    return <div>hello</div>;
  }
  role = "user";

  console.log("🚀 ~ file: layout.jsx:28 ~ RootLayout ~ role:", role);
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        {/* <Provider session={session}> */}
        {/* <Navbar>{children}</Navbar> */}
        <Navbar session={session}>{children}</Navbar>
        {/* <About session={session} /> */}
        <Footer />
        {/* </Provider> */}
      </body>
    </html>
  );
}
